services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hazem
      POSTGRES_DB: tournify
      POSTGRES_PASSWORD: test123
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  testdb:
    image: postgres
    container_name: postgresdb_test
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: hazem2
      POSTGRES_DB: tournify_test
      POSTGRES_PASSWORD: test1234

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ben_abdelhafidh_hazem@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
